### ISSUE TITLE
feat request: support HexBytes more

### ISSUE THREAD

**Issue by antazoey** [mikeshultz/ledger-eth-lib#43]
so many places have `assert type(thing) == bytes`
if we did `assert isinstance(thing, bytes)`, it'd allow HexBytes

But also, assertion errors are not the best to encounter, the message is not helpful without digging into the tb; a `TypeError("Expecting bytes, not blah blah")` would be better for the lib

**Comment by antazoey** [comment]
`isinstance()` will work for mypy too! And you dont have to explicitly support HexByes, it will just work.
basically all mypy assertions that use `type()` instead of instance

**Comment by mikeshultz** [comment]
> `isinstance()` will work for mypy too!

I get that, I only brought that up to say that you shouldn't be seeing these assertion errors.  They aren't for users.

> And you dont have to explicitly support HexByes, it will just work.

What does this mean?

**Comment by antazoey** [comment]
The assertions will be there unless you compile in optimized mode.
And I mean I will be able to pass sub-classes instead of the asserted type and everything will work but you won't have to include the mentioning of HexBytes anywhere because itll still work but it wont fail the type check

**Comment by mikeshultz** [comment]
Oh, I think I misunderstood.  `isinstance(x, bytes)` would allow HexBytes.  You were not requesting adding `isinstance(x, HexBytes)` to allow derivatives of `HexBytes`.  Yeah, I'm good with that.

Also, deja vu.
